name = "LotSizingProblems"
uuid = "623f94cc-a1ff-4b98-b6ae-5db88bddaaf7"
authors = ["Rafael Martinelli"]
version = "0.0.1"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
p7zip_jll = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"

[compat]
julia = "1"
